In [1]:
import pandas as pd

In [55]:
df = pd.read_csv("./raw/ACSST5Y2020.S1901-income.csv").transpose()

In [56]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
Label (Grouping),Total,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median income (dollars),Mean income (dollars),PERCENT ALLOCATED,Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months
ZCTA5 78610!!Households!!Estimate,"13,284",3.8%,1.9%,3.3%,4.4%,9.2%,18.7%,17.4%,20.4%,10.8%,10.2%,"84,114","108,413",NaN,29.7%,(X),(X)
ZCTA5 78610!!Households!!Margin of Error,±716,±1.8,±1.5,±1.3,±1.5,±2.4,±4.2,±3.1,±3.3,±2.8,±3.8,"±5,435","±10,071",NaN,(X),(X),(X)
ZCTA5 78610!!Families!!Estimate,"10,269",1.4%,1.5%,2.5%,3.7%,9.1%,16.2%,19.0%,21.6%,12.2%,12.9%,"94,644","119,633",NaN,(X),29.9%,(X)
ZCTA5 78610!!Families!!Margin of Error,±658,±0.9,±1.4,±1.2,±1.5,±3.0,±4.1,±3.9,±3.7,±3.6,±4.7,"±7,764","±12,891",NaN,(X),(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Travis County, Texas!!Families!!Margin of Error","±3,204",±0.3,±0.2,±0.3,±0.4,±0.5,±0.6,±0.7,±0.8,±0.6,±0.6,"±1,468","±1,988",NaN,(X),(X),(X)
"Travis County, Texas!!Married-couple families!!Estimate","213,047",1.3%,0.8%,2.3%,3.3%,5.6%,12.0%,12.9%,24.8%,14.8%,22.2%,"121,569","157,503",NaN,(X),(X),(X)
"Travis County, Texas!!Married-couple families!!Margin of Error","±3,354",±0.3,±0.2,±0.3,±0.3,±0.5,±0.7,±0.8,±1.0,±0.8,±0.7,"±2,021","±2,552",NaN,(X),(X),(X)
"Travis County, Texas!!Nonfamily households!!Estimate","211,387",8.7%,4.0%,7.9%,9.0%,14.2%,19.5%,13.0%,13.9%,4.7%,5.2%,"56,587","76,603",NaN,(X),(X),29.0%
"Travis County, Texas!!Nonfamily households!!Margin of Error","±3,384",±0.6,±0.5,±0.5,±0.6,±0.7,±0.8,±0.7,±0.7,±0.4,±0.4,"±1,239","±1,585",NaN,(X),(X),(X)

In [57]:
# df.columns = df.columns.str.replace("Total:!!","")
# df.columns = df.columns.str.replace(":!!"," ")
# df.columns = df.columns.str.replace(":"," ")
df = df.rename(columns={df.columns[i]: df.iloc[0][i] for i in range(len(df.columns))})
df = df.reset_index()
df = df.replace("ZCTA5 ","",regex=True)
df = df.replace("±", "", regex=True)
df = df.rename(columns={"index": "Zip Code"})

In [58]:
df = df.drop(0)

In [59]:
df

,Zip Code,Total,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median income (dollars),Mean income (dollars),PERCENT ALLOCATED,Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months
1,78610!!Households!!Estimate,"13,284",3.8%,1.9%,3.3%,4.4%,9.2%,18.7%,17.4%,20.4%,10.8%,10.2%,"84,114","108,413",NaN,29.7%,(X),(X)
2,78610!!Households!!Margin of Error,716,1.8,1.5,1.3,1.5,2.4,4.2,3.1,3.3,2.8,3.8,"5,435","10,071",NaN,(X),(X),(X)
3,78610!!Families!!Estimate,"10,269",1.4%,1.5%,2.5%,3.7%,9.1%,16.2%,19.0%,21.6%,12.2%,12.9%,"94,644","119,633",NaN,(X),29.9%,(X)
4,78610!!Families!!Margin of Error,658,0.9,1.4,1.2,1.5,3.0,4.1,3.9,3.7,3.6,4.7,"7,764","12,891",NaN,(X),(X),(X)
5,78610!!Married-couple families!!Estimate,"8,219",0.7%,1.0%,1.6%,3.3%,7.7%,12.7%,20.2%,23.3%,13.8%,15.6%,"102,268",N,NaN,(X),(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,"Travis County, Texas!!Families!!Margin of Error","3,204",0.3,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.6,0.6,"1,468","1,988",NaN,(X),(X),(X)
485,"Travis County, Texas!!Married-couple families!...","213,047",1.3%,0.8%,2.3%,3.3%,5.6%,12.0%,12.9%,24.8%,14.8%,22.2%,"121,569","157,503",NaN,(X),(X),(X)
486,"Travis County, Texas!!Married-couple families!...","3,354",0.3,0.2,0.3,0.3,0.5,0.7,0.8,1.0,0.8,0.7,"2,021","2,552",NaN,(X),(X),(X)
487,"Travis County, Texas!!Nonfamily households!!Es...","211,387",8.7%,4.0%,7.9%,9.0%,14.2%,19.5%,13.0%,13.9%,4.7%,5.2%,"56,587","76,603",NaN,(X),(X),29.0%
488,"Travis County, Texas!!Nonfamily households!!Ma...","3,384",0.6,0.5,0.5,0.6,0.7,0.8,0.7,0.7,0.4,0.4,"1,239","1,585",NaN,(X),(X),(X)

In [60]:
zipcodes = [df['Zip Code'][i].split('!!')[0] for i in df.index]
label = [df['Zip Code'][i].split('!!')[1] for i in df.index]
grouping = [df['Zip Code'][i].split('!!')[2] for i in df.index]

In [61]:
df['Zip Code'] = zipcodes
df.insert(1,'Label',label)
df.insert(2,'Grouping',grouping)

In [62]:
df

,Zip Code,Label,Grouping,Total,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median income (dollars),Mean income (dollars),PERCENT ALLOCATED,Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months
1,78610,Households,Estimate,"13,284",3.8%,1.9%,3.3%,4.4%,9.2%,18.7%,17.4%,20.4%,10.8%,10.2%,"84,114","108,413",NaN,29.7%,(X),(X)
2,78610,Households,Margin of Error,716,1.8,1.5,1.3,1.5,2.4,4.2,3.1,3.3,2.8,3.8,"5,435","10,071",NaN,(X),(X),(X)
3,78610,Families,Estimate,"10,269",1.4%,1.5%,2.5%,3.7%,9.1%,16.2%,19.0%,21.6%,12.2%,12.9%,"94,644","119,633",NaN,(X),29.9%,(X)
4,78610,Families,Margin of Error,658,0.9,1.4,1.2,1.5,3.0,4.1,3.9,3.7,3.6,4.7,"7,764","12,891",NaN,(X),(X),(X)
5,78610,Married-couple families,Estimate,"8,219",0.7%,1.0%,1.6%,3.3%,7.7%,12.7%,20.2%,23.3%,13.8%,15.6%,"102,268",N,NaN,(X),(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,"Travis County, Texas",Families,Margin of Error,"3,204",0.3,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.6,0.6,"1,468","1,988",NaN,(X),(X),(X)
485,"Travis County, Texas",Married-couple families,Estimate,"213,047",1.3%,0.8%,2.3%,3.3%,5.6%,12.0%,12.9%,24.8%,14.8%,22.2%,"121,569","157,503",NaN,(X),(X),(X)
486,"Travis County, Texas",Married-couple families,Margin of Error,"3,354",0.3,0.2,0.3,0.3,0.5,0.7,0.8,1.0,0.8,0.7,"2,021","2,552",NaN,(X),(X),(X)
487,"Travis County, Texas",Nonfamily households,Estimate,"211,387",8.7%,4.0%,7.9%,9.0%,14.2%,19.5%,13.0%,13.9%,4.7%,5.2%,"56,587","76,603",NaN,(X),(X),29.0%
488,"Travis County, Texas",Nonfamily households,Margin of Error,"3,384",0.6,0.5,0.5,0.6,0.7,0.8,0.7,0.7,0.4,0.4,"1,239","1,585",NaN,(X),(X),(X)

In [63]:
df_err = df.copy()

In [28]:
for index, row in df.iterrows():
    if index == len(df) - 3:
            df.iloc[index][1:] = df.iloc[index + 1][1:]
            df_err.iloc[index][1:] = df_err.iloc[index + 2][1:]
            break
    else:
            df.iloc[index][1:] = df.iloc[index + 1][1:]
            df_err.iloc[index][1:] = df_err.iloc[index + 2][1:]

In [66]:
drop_idx = [i for i in range(2,len(df),2)]
drop_idx_err = [i for i in range(1,len(df),2)]
df = df.drop(drop_idx)
df_err = df_err.drop(drop_idx_err)

In [68]:
df_err

,Zip Code,Label,Grouping,Total,"Less than $10,000","$10,000 to $14,999","$15,000 to $24,999","$25,000 to $34,999","$35,000 to $49,999","$50,000 to $74,999","$75,000 to $99,999","$100,000 to $149,999","$150,000 to $199,999","$200,000 or more",Median income (dollars),Mean income (dollars),PERCENT ALLOCATED,Household income in the past 12 months,Family income in the past 12 months,Nonfamily income in the past 12 months
2,78610,Households,Margin of Error,716,1.8,1.5,1.3,1.5,2.4,4.2,3.1,3.3,2.8,3.8,"5,435","10,071",NaN,(X),(X),(X)
4,78610,Families,Margin of Error,658,0.9,1.4,1.2,1.5,3.0,4.1,3.9,3.7,3.6,4.7,"7,764","12,891",NaN,(X),(X),(X)
6,78610,Married-couple families,Margin of Error,694,0.6,1.3,1.3,1.7,3.2,3.2,4.4,4.4,4.2,5.4,"8,098",N,NaN,(X),(X),(X)
8,78610,Nonfamily households,Margin of Error,521,7.2,4.7,5.0,4.6,6.6,9.9,5.1,6.5,3.0,1.3,"11,162","10,237",NaN,(X),(X),(X)
10,78612,Households,Margin of Error,430,2.4,2.8,4.3,3.1,4.6,6.1,5.7,6.6,2.7,3.0,"9,650","9,339",NaN,(X),(X),(X)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,78759,Nonfamily households,Margin of Error,757,1.8,1.2,3.1,1.9,3.1,4.1,2.6,2.4,1.6,2.5,"3,415","5,619",NaN,(X),(X),(X)
482,"Travis County, Texas",Households,Margin of Error,"1,904",0.3,0.2,0.3,0.3,0.4,0.5,0.5,0.5,0.4,0.4,972,"1,313",NaN,(X),(X),(X)
484,"Travis County, Texas",Families,Margin of Error,"3,204",0.3,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.6,0.6,"1,468","1,988",NaN,(X),(X),(X)
486,"Travis County, Texas",Married-couple families,Margin of Error,"3,354",0.3,0.2,0.3,0.3,0.5,0.7,0.8,1.0,0.8,0.7,"2,021","2,552",NaN,(X),(X),(X)
488,"Travis County, Texas",Nonfamily households,Margin of Error,"3,384",0.6,0.5,0.5,0.6,0.7,0.8,0.7,0.7,0.4,0.4,"1,239","1,585",NaN,(X),(X),(X)

In [69]:
df.to_csv("./clean/ACSST5Y2020.S1901-income_clean.csv")
df_err.to_csv("./clean/ACSST5Y2020.S1901-income_err_clean.csv")

In [2]:
"sexbyage2020_noerr_clean.csv"

['sexbyage2020_noerr_clean', 'csv']

In [31]:
df_err

,Zip Code,Total,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,Two or more races Two races including Some other race,"Two or more races Two races excluding Some other race, and three or more races"
0,78610,"1,996","1,514",594,233,315,30,449,"1,345","1,183",492
3,78612,"2,025","1,146",622,81,198,22,"1,414","1,215","1,207",116
6,78613,"1,563","2,419",752,206,"1,091",211,848,"1,106",819,957
9,78615,490,340,14,167,14,14,42,315,316,7
12,78617,"2,213","1,868",316,46,284,26,"2,125",921,891,142
...,...,...,...,...,...,...,...,...,...,...,...
168,78756,"1,124",694,145,27,222,20,60,473,377,161
171,78757,"2,406","1,395",588,26,259,26,957,"1,449","1,370",244
174,78758,"3,125","2,255",965,324,"1,024",48,"1,498","1,436","1,331",388
177,78759,"2,097","1,626",407,20,674,23,429,921,708,608
180,"Travis County, Texas",*****,"6,261","1,808","1,218","1,560",343,"5,152","5,205","5,052","2,750"

183